name: Format
on: [push, pull_request]
jobs:
  format:
    name: Format
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check format
        run: |
          ./scripts/format.sh
