name: Format
on: [push, pull_request]
jobs:
  format:
    name: Format
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Check format
        run: |
          ./scripts/format.sh
