name: Format
on: [push, pull_request]
jobs:
  format:
    name: Format
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt update || true
          sudo apt --yes --no-install-recommends install clang-format
      - name: Check format
        run: |
          ./scripts/format.sh
