name: Format
on: [push, pull_request]
jobs:
  format:
    name: Format
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        # FIXME The images contain a custom version of Clang, which we have to remove first (see https://github.com/actions/virtual-environments/blob/master/images/linux/scripts/installers/clang.sh).
        run: |
          sudo apt update || true
          sudo apt --yes purge clang-6.0 lldb-6.0 lld-6.0
          sudo apt --yes autoremove
          sudo apt --yes --no-install-recommends install clang-format
      - name: Check format
        run: |
          ./scripts/format.sh
